### ISSUE TITLE
Update the way a navigation route is registered

### ISSUE THREAD

**Issue by delawski** [xwp/pwa-wp#319]
After updating PWA plugin from version 0.3 to 0.4 or 0.5, the following error is thrown in the console during a SW installation:
```
wp_service_worker=1:411 Uncaught TypeError: wp.serviceWorker.routing.registerNavigationRoute is not a function
    at ?wp_service_worker=1:411
    at ?wp_service_worker=1:477
```

It seems that [the way the navigation route is registered](https://github.com/GoogleChromeLabs/pwa-wp/blob/develop/wp-includes/js/service-worker-navigation-routing.js#L161-L166) is [no longer supported in Workbox 5](https://github.com/GoogleChrome/workbox/issues/2095).

The SW is successfully installed with the following change:

```diff
- wp.serviceWorker.routing.registerNavigationRoute(
-   navigationRouteEntry.url,
-   {
-     denylist,
-   }
- );
+ wp.serviceWorker.routing.registerRoute(
+   new wp.serviceWorker.routing.NavigationRoute(
+     wp.serviceWorker.precaching.createHandlerBoundToURL(
+      navigationRouteEntry.url
+     ),
+     {
+       denylist,
+     }
+   )
+ );
```
